 sudo: false  
 language: java   
 install: true 
 cache:  
  directories:  
   - $HOME/.m2  
 env:  
  global:  
   - DISPLAY=:99.0  
 before_install:  
  - sh -e /etc/init.d/xvfb start
 script:    
  - mvn -B -V verify    

