 sudo: false
 dist: trusty
 language: java
 jdk: oraclejdk8
 install: true
 cache:
  directories:
   - $HOME/.m2
 env:
  global:
   - DISPLAY=:99.0
   - MAVEN_OPTS="-Xmx4g"
 before_install:
  - sh -e /etc/init.d/xvfb start
 script:
  - mvn -B -V verify
 after_failure:
  - grep -r --include=TEST-*.xml -h -A9999 -B9999 -E '<error|<failure' ./

